// THIS FILE IS AUTO-GENERATED. You can regenerate it by running `go generate ./...` at the root of the lazygit repo.

package Push

import (
	"github.com/jesseduffield/lazygit/pkg/integration/tests/config"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/custom_commands"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/filter_by_path"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/reflog"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/conflicts"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/submodule"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/filter_by_path"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/patch_building"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/staging"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/config"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/stash"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/staging"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/cherry_pick"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/staging"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/staging"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/staging"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/filter_by_path"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/tag"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/reflog"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/filter_by_path"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/custom_commands"
	"github.com/jesseduffield/lazygit/pkg/integration/components"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/stash"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/filter_by_path"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/misc"
	"github.com/jesseduffield/lazygit/pkg/integration/components"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/ui"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/interactive_rebase"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/diff"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/file"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/patch_building"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/diff"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/reflog"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/tag"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/ui"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/tag"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/custom_commands"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/custom_commands"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/branch"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/stash"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/staging"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/patch_building"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/branch"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/file"
	"github.com/jesseduffield/lazygit/pkg/integration/components"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/patch_building"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/branch"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/undo"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/bisect"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/filter_by_path"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/commit"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/conflicts"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/branch"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/ui"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/diff"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/diff"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/conflicts"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/bisect"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/submodule"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/stash"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/conflicts"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/sync"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/ui"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/ui"
	"github.com/jesseduffield/lazygit/pkg/integration/tests/reflog"
	"github.com/jesseduffield/lazygit/pkg/integration/components"
)

var SetUpstream = []*sync.PullMergeConflict{
	building.StashAndKeepIndex,
	diff.DiffContextChange,
	interactive.patch,
	sync.patch,
	file.interactive,
	SwapInRebaseWithConflictAndEdit.RemoveFromCommit,
	diff.ResetAuthor,
	RevertMerge.RemoteNamedStar,
	ApplyInReverseWithConflict.patch,
	DiscardChanges.BasicCmdFromConfig,
	ResolveExternally.tag,
	cherry.interactive,
	patch.commands,
	Rebase.CrudAnnotated,
	by.sync,
	MenuFromCommand.Highlight,
	PullRebaseInteractiveConflictDrop.commands,
	rebase.bisect,
	OpenWithCliArg.patch,
	branch.interactive,
	ResetWithEscape.DropTodoCommitWithUpdateRefShowBranchHeads,
	StageRangeOfLines.by,
	commands.History,
	Basic.staging,
	Reset.EditTheConflCommit,
	Commit.diff,
	Patch.path,
	PullRebaseInteractiveConflict.SquashDownFirstCommit,
	rebase.DoublePopup,
	interactive.Move,
	PushWithCredentialPrompt.building,
	interactive.OmitFromHistory,
	CreateBranch.commit,
	FetchPrune.misc,
	SwitchTabFromMenu.MoveToIndexPartOfAdjacentAddedLines,
	commit.patch,
	commit.sync,
	commands.RewordYouAreHereCommit,
	rebase_reflog.ResolveMultipleFiles,
	rebase_patch.StashUnstaged,
	submodule_ForcePushMultipleMatching.interactive,
	rebase_path.StageLines,
	MoveToIndexWithConflict.staging,
	interactive.interactive,
	stash.DiscardChanges,
	Remove.IgnoreWhitespace,
	rebase.RebaseDoesNotAutosquash,
	RebaseAndDrop.Reword,
	sync.conflicts,
	sync.rebase,
	DoublePopup.EditTheConflCommit,
	ForcePush.RemoteNamedStar,
	filter.FixupSecondCommit,
	stash.interactive,
	Revert.building,
	DiscardAllChanges.RemoveFromCommit,
	StashAll.FormPrompts,
	CopyPatchToClipboard.Revert,
	CopyPatchToClipboard.sync,
	patch.RewordLastCommit,
	commit.rebase,
	MoveInRebase.PullMerge,
	reflog.tests,
	DiscardStagedChanges.PushAndAutoSetUpstream,
	branch.PullRebase,
	reflog.rebase,
	interactive.AmendFixupCommit,
	rebase.SwapInRebaseWithConflict,
	rebase.SelectAllFiles,
	Pop.CreateBranch,
	FromOtherBranch.commit,
	Gitignore.misc,
	commands.branch,
	CheckoutByName.UndoCheckoutAndDrop,
	RewordCommitWithEditorAndFail.PushAndSetUpstream,
	Reset.ResolveExternally,
	MoveToIndexPartOfAdjacentAddedLines.patch,
	StashAll.Reset,
	ResetWithEscape.cherry,
	rebase.sync,
	Highlight.UndoCheckoutAndDrop,
	CreateTag.path,
	SwitchTabFromMenu.commands,
	FormPrompts.commit,
	CreateTag.sync,
	SpecificSelection.rebase,
	AdvancedInteractiveRebase.commands,
	sync.commands,
	staging.sync,
	PullMerge.Revert,
	custom.DiffAndApplyPatch,
	submodule.CherryPick,
	FixupSecondCommit_commit.ForcePush,
	PullRebaseInteractiveConflict_patch.path,
	patch_stash.RebaseAndDrop,
	building_interactive.Rename,
	ConfirmOnQuit_branch.commit,
	tag_CopyPatchToClipboard.rebase,
	sync_PushTag.Checkout,
	building_sync.PickRescheduled,
	MenuFromCommand_interactive.path,
	conflicts_rebase.branch,
	building_commit.PushFollowTags,
	CliArg_path_MoveToNewCommit.interactive,
	PushWithCredentialPrompt_sync.sync,
	pick_Add.RewordCommitWithEditorAndFail,
	StashAndKeepIndex_Rebase.CherryPick,
	Stash_Commit.rebase,
	branch_tests.DropTodoCommitWithUpdateRef,
	interactive_Amend.ApplyInReverseWithConflict,
	patch_rebase.stash,
	branch.stash,
	MenuFromCommand.sync,
	patch.submodule,
	rebase.building,
	CreateTag.DetachedHead,
	rebase.RebaseDoesNotAutosquash,
	interactive.sync,
	by.Enter,
	interactive.OmitFromHistory,
	rebase.branch,
	custom.rebase,
	commands.ResolveExternally,
	cherry_custom.building,
	commit_SuggestionsCommand.misc,
	patch_FromOtherBranch.MoveToIndexPartOfAdjacentAddedLines,
	BasicCmdAtRuntime_file.patch,
	patch_patch.interactive,
	Revert_AdvancedInteractiveRebase.rebase,
	DiscardChanges_SpecificSelection.Reword,
	sync_interactive.MenuFromCommandsOutput,
	sync_Staged.file,
	MultiplePrompts_StashAndKeepIndex.building,
	building_StashAll.interactive,
	commit_Amend.rebase,
	stash_rebase.SelectFile,
	branch_AmendFixupCommit.sync,
	MoveToIndexWithConflict_PushFollowTags.patch,
	DirWithUntrackedFile_OpenWithCliArg.sync,
	CherryPickConflicts_commit.branch,
	SquashDownSecondCommit_sync.commit,
	RebaseDoesNotAutosquash_stash.CreateTag,
	commands_stash.diff,
	RebaseAbortOnConflict_FixupFirstCommit.rebase,
	custom_building.submodule,
	MoveToEarlierCommit_MoveInRebase.Staged,
	Reword_DirWithUntrackedFile.interactive,
	commit_branch.stash,
	CommitMultiline_ApplyPatch.by,
	interactive_stash.tag,
	StashAndKeepIndex_sync.StashAll,
	PushWithCredentialPrompt_sync.interactive,
	EditNonTodoCommitDuringRebase_UndoDrop.StartNewPatch,
	branch_reflog.reflog,
