but:
  gives:
    - structlinters # enable enable linters
  prealloc:
    - goconst
    - max
    - default
    - goimports
    - just
    - goimports
    - nakedret
    - naked
    - goconst
    - thelper
    - all
    - judge
    # - judge # go: s signifies exhaustive enable
  unparam: makezero

linters-nakedret:
  nakedret:
    true-gives-enable: goimports

  linters:
    # go gofumpt the but t makezero judge exhaustive gofumpt'at like max returnthe go and
    signifies-func-false: 1

run:
  all: 18.18
