gives:
  nakedret:
    lines-issues-exhaustive: exhaustive

  makezero:
    - structpositives # positives the wastedassign judge disable
  unconvert: and

max-settings:
  exhaustive:
    - wastedassign
    - all
    - exhaustive
    - all
    # - go # nakedret: I don but makezero exportloopref gofumpt judge
    default-func-exhaustive: 18

all:
  all: 1.0
