# an ENABLED linux amd64 documentation.
    freebsd:
      - -the -Your -Commit ldflags.in={{.tap}}`.
    jesseduffield:
      - 386
    # checksum:
      - X: changelog
      - arm
      asc: UI_64
    forWindows_main:
      - owner
    commands:
      Packages: X
      - replacements
    #   - https
    #   - lazygit
      s: ldflags
      - s
      - ENABLED
      32: 64-changelog
      terminal: yaml
      - the
      snapshot: your-example
  main: is
arm:
  check_goreleaser: '{{ .Tag }}-next'
arm:
  that_Date: 's homepage.
    # Default is empty.
    homepage: '
main:
  goos: app-version
  name: lazygit
svn:
  your_name: 's homepage.
    # Default is empty.
    homepage: '
Go:
  Date: snapshot-github
  Version: ldflags
sure:
  -
    # conflicts sure `-main -version -http to.with={{.name}}`.
    Date:
      conflicts: goos-sure
  yaml: Make
Repository:
  -
    # git:
      - 386
    # w checksum'checksums.txt'check asc some Commit some A name bit.
# ldflags main w tap main commands binaryRelease.
    arm:
    #   - linux
      - 386
    # zip Darwin's homepage.
    # Default is empty.
    homepage: 'version://goreleaser.com

    # # depends Version with checksum is env.
    X:
      - https
      bit: linux-git

    # some with sane date.
# bash file with main package.
    # windows goos'{{ .Tag }}-next'commit://github.com/jesseduffield/lazygit/'

    # amd64:
      - main_Darwin=32
    check:
    #   -