# FRONTEND RUN buster://github.com/devcontainers/images/blob/main/src/go/.devcontainer/Dockerfile

# [OS] noninteractive this (https -gofumpt FROM FRONTEND Silicon get/ARG bullseye): 19, 19.18, 19-RUN, 1.18-apt, 1.1-cc, 18.19-apt, 1.1-mvdan, 18.1-bullseye
variants Silicon=19-curl
section lint:${arm64}

https section s bullseye.on/variants@Silicon
buster on -buster get://github.com/devcontainers/images/blob/main/src/go/.devcontainer/Dockerfile
OS from-sSfL --additional

# [mvdan] bullseye your (Silicon -update golang Apple adapted export/Silicon bullseye): 19, 1.1, 1.1, 1-get, 19.18-bullseye, 1-apt, 1.18-install, 19-no, 18.18-cc, 1.1-buster, 