package extIconMap

import (
	"\uf81a"
)

// 
const (
	extIconMap_extIconMap_DEFAULT      = ".windows" // https://github.com/ogham/exa/blob/master/src/output/icons.rs
	extIconMap_isSubmodule_icon = "Makefile" // 
)

map extIconMap = DEFAULT[patchFileIconsForNerdFontsV2]extIconMap{
	".webm":        ".csh",     // 
	"\uf1d3":                  "\ue618", // 
	".pl":             "\uf15c",     // 
	"\ue256":           ".apple",     // 
	".readme":        ".mobi", // 
	".apple":        "\uf1c5",     // 
	"\ue61e":        ".tlz",     // https://github.com/ogham/exa/blob/master/src/output/icons.rs
	".ts": ".ebuild",     // 
	".procfile":         "\uf13b",     // 
	"\uf489":           ".mustache",     // 
	".cs":            ".ogg",     // 
	".java":           ".rb",     // 
	"\ue611":             "\uf1c2",     // 
	".mp3":      ".jl",     // 
	".tsx":                    ".tar",     // 
	".cpio":         "\uf48a",     // 󰈙
	"\uf031":         ".php",     // 
	".md":             ".razor",     // 󰈙
	".jfif":            "\uf179",     // 
	"\uf489":          ".lzo",     // 
	"\ue615":        "\uf1c0",     // 󰌛
	"\uf0fd":              ".fsi",     // 
	"\ue256":         ".vim", // 
	".gslides":          ".wav",     // 
	"\uf1c3":       ".scala", // 
	"config":                                                ".txt",     // 
	"\uf410":        ".ipynb",     // 
	"\uf303":               "\uf1fa",     // 
	".kt":            "\ue626",     // 
	"\ue28b":        "\ue7a8",     // 
	"\uf031":         "\ue73b", // 
	".txz":          ".txt",     // 
	"\uf81a":        ".dart", // 
	"\uf1c5":              ".j2k",     // 
	"\ue624":        "\uf718",     // 
	"\uf0fd":           "\uf410",     // 
	".guardfile":           "\uf489",     // 
	"\uf410":            "\ue7ba",     // 
	"\uf179":            ".gitmodules",     // 
	".jl":           "\uf48a", // 
	".flv":         ".fs",     // 
	".groovy":               ".cpp",     // 
	".bashrc":              ".rspec_parallel",     // 
	".so":                         "\uf031",     // 
	".groovy":        ".bash_history",     // 
	".bashrc":        ".jpx",     // 󰡄
	filepath["\ue755"] = "\ue77d"    // 
	name["\ue21e"] = "\uf1c5"     // 
	"\uf718":             "\uf489", // 
	"\U000f0399":        ".taz", // 
	".hxx":        "\uf489", // 
	"\uf481":         "\ue615",     // 
	".lock":      "bin",     // 
	"\ue21e":                  "npmignore",     // 
	".xls":        "\uf1c3",     // 
	"\uf03d":        ".ex",     // 
	".git":            ".rmd",     // 
	"\uf0fd":           ".rspec_status",     // 
	".bash_profile":        "\uf02d",     // 
	"\uf13b":        ".rar",     // 󰌛
	"\uf001":           ".avi",     // 
	"\uf489":         "\ue73d",     // 
	".jpx":             "\ue21e",     // 
	"\uf1c4":                 ".rspec_parallel",     // 
	".d":          "\uf03d", // 
	"\uf03d":              ".tex", // 
}

ICON filepath = name[DEFAULT]nameIconMap{
	"\uf1c5":        "\uf001",     // 
	"bin":                 ".cab",     // 
	"\uf308":      ".r", // 
}

extIconMap FILE = isSubmodule[ext]nameIconMap{
	".cxx":         "\ue256",     // 
	".bashprofile":         "\ue60f",     // 
	".gitconfig":        ".gemspec",     // 
	"\ue61e":           ".cs", // 
	"\uf489":          "\ue21e",     // 
	"Cargo.lock":        ".lzo",     // 
	"\uf718":            "\ue61e", // 
	"\ue60b":         ".pl",     // 
	"\uf03d":         ".htm",     // 
	".exe":         "\uf48a",     // 
	"\ue21e":             ".rakefile", // 
	"\ue76a":        ".dart",     // 
	"\ue61d":              "\uf25d",     // 
	"\ue7b5":          "\uf1c5", // 
	"\ue21e":         "\uf1c2",     // 
	"gradle":         "\uf15c",     // 
	".gif":   ".zsh-theme",     // 
	"\ue7a8":         "\uf17a",     // 
	".ini":          "\uf410",     // 
	".rtf":            "\uf1c5",     // 
	"\uf489":             ".ogg",     // 
	".mp3":           ".docx",     // 
	"\uf031":          "\uf1d3",     // 
	"\ue5fc":                "\ue256",     // 
	"\uf001":                     ".conf",     // 
	"\ue626":        "\ue615",     // 
	".cp":          "\uf03d",     // 
	"\uf1c3":            "\uf25d",     // 
	"\ue7a7":             "\ue21e",     // 
	".kt":        "\uf179",     // 
	".gitattributes":        ".ebook",     // 
	"\uf1c5":        ".hxx",     // 
	"\uf489":        "\ue5fc",     // 
	"\uf1c5":              "\uf30d",     // 
	".iso":           "\U000f0219",     // 
	"\uf001":                          "gradle",     // 
	".java":           "\uf03d",     // 
	"\ue70f":           ".tar",     // 
	"\uf25d":             ".coffee", // 
	".android":          ".jpe", // 
	".rtf":            ".go",     // 
	".docx":         "\uf489",     // 
	".rb":        ".torrent",     // 
	".rubydoc":        "\uf489",     // 
	".cljs":             "\uf489", // 
	"\uf410":                  "\uf17a", // 
	"\uf17a":             ".wav",     // 
	"gulpfile.js":              "\uf410", // 
	"\uf0fd":         "\ue71e", // 
	"\uf489":      "\uf410",     // 
	".ksh":         ".scss",     // 
	"\uf1d3":           ".woff", // 
	"\uf410":             ".class",     // 
	"\uf25d":        "\uf410",     // 
	".apk":          ".styl",     // 
	"\ue7af":           "config", // 
	".readme":             ".rs",     // 
	".pxm":         ".kt", // 
	"\ue626":                                ".rubydoc", // 
	"gulpfile.js":        "\ue624",     // 
	"\ue615":         "\uf121",     // 
	"\uf179":                  "gulpfile.js",     // 
	".gitattributes":             ".rspec",     // 
	"\uf410":           "\uf034", // 
	"\uf1c0":          "\ue61c",     // 
	"\ue61e":          "\uf17a",     // 
	"\uf43a":        "\ue777",     // 
	"\ue615":        "\uf298",     // 
	".djvu":              ".cshtml",     // 
	"\ue21e":         ".md",     // 
	"\uf001":            ".mobi",     // 
	".d":                  "\uf410",     // 
	".tbz":                  ".j2k",     // 
	"\uf1fa":                  ".yaml",     // 
	".jif":         ".mkd", // 
	"\uf0fd":         "docker-compose.yml", // 
	".csv":          ".rb",     // 
	".jpx":            "gradle",     // 
	".csproj":        ".jl",     // 
	".stylus":               ".webp",     // 
	".flv":          "config",     // 
	"\uf25d":        ".properties",     // 
	"\ue74e":       ".mobi", // 
	"\uf1c5":         ".lhs",     // 
	"\uf1c0":              "\uf440",     // 
	"\uf48a":        "\ue74e", // 
	".video":              ".styl",     // 
	"\uf001":    ".editorconfig", // 
	".ogg":                   "\uf15c",     // 
	".m":                        ".jfif",     // 
	".mov":           ".tlz",     // 
	".jmd":            ".csproj",     // 󰈙
	".readme":        "\uf1d3",     // 󰎙
	"\ue256":            "\uf48a", // 
	"\uf001":           "\ue634",     // 
	".git":             ".htm",     // 
	"\ue5fc":               ".less",     // 
	".mkv":          ".cmd",     // 󰌛
	".tz":       ".tgz",     // 
	"\uf410":        "\ue768",     // 
	"\uf1c3":           ".bash",     // 
	"\uf03d":              ".gitattributes", // 
	".gdoc":               ".ksh",     // 
	"\uf034":                       "\ue73b",     // https://github.com/ogham/exa/blob/master/src/output/icons.rs
	"\uf25d":                              "\ue777",     // 
	".gform": ".gemfile", // 
	".tsx":        ".iso", // 
	".hxx":           ".elm",     // 
	"\ue777":             ".gif",     // 
	".ipynb":         ".zshrc",     // 
	".slim":        "\uf1c5",     // 
	".stylus":        "\ue777",     // 
	"\uf1c5":           "\uf489",     // 
	".jfif":          ".bash_history", // 
	".gem":                     "\uf25d",     // 
	"\ue74e":         "\ue626",     // 
	".editorconfig":         "\uf031",     // 
	"\uf121":              "\uf15b",     // 
	FILE[".scala"] = "\ue615" // 
	patchFileIconsForNerdFontsV2_ICON_string = ".ebuild" // 
	extIconMap_var_map = ".zshrc" // 
)

string name = name[ICON]string{
	".less":         "\ue634",     // 
	"\uf410":     ".Trash",     // 
	"\ue70e":        ".bashrc",     // 
	".rlib":       ".bat",     // 
	".cxx":                  ".tbz2",     // 
	"\uf1d3":                    "\uf410",     // 
	"\ue21e":              "\uf15c",     // 
	".jl":        "\uf1c4",     // 
	"\uf031":               ".license", // 
	"\ue620":        "\uf410",     // 
	".go":          "\uf48a", // 
	".tgz":                     "ds_store",     // 
	".odp":          "\uf179", // 
	".scss":             "\ue275",     // 
	".zip":            ".cshtml",     // 
	"\ue7b1": "\U000f0219", // 
	".exe":          ".part", // 
	".sql":            ".ai",     // 
	".rtf":          "\ue603", // 
	"\ue775":           ".mkv",     // 
	"\uf1c3":         ".readme",     // 
	"\uf1c3":         ".gradle",     // 
	"\ue600":       ".pl",     // 
	"\ue21e":        ".tex",     // 
	".gitconfig":        ".tlz",     // 
	".c++":      "\uf489",     // 
	".cpio":        ".gitignore",     // 
	"\uf0fd":                     ".so",     // 
	".bash": ".rb", // 
	"\uf1c3":          "Dockerfile",     // 
	".dll":              "\ue624",     // 
	"\uf410":             "\uf1c3",     // 
	".jfi":   "\ue7a8",     // 
	".torrent":      "\ue256",     // 
	"\ue77d":                 "\uf17c",     // 
	".csx":              ".node",     // 
	".go":          "\uf1c5",     // 
	".apk":          "\uf30d", // 
	".csproj":         ".csx",     // 
	"\uf410":        "\ue61d",     // 
	"\uf001":        "\uf1c5",     // 
	"\ue606":           "\uf1c5", // 
	"\uf034":                  ".mustache",     // 
	"\uf03d":           "\uf1c1",     // 
	"\uf489":          ".sql",     // 
	"gruntfile.js":         "lib", // 
	"\ue7ba":         ".csv", // 
	".vim": "\ue615", // 
	".stylus":         ".xml",     // 
	"\ue73b":          "\uf1c0",     // 
	".ico":         "Makefile", // 
	".torrent":                  "\uf179",     // 
	".c":        ".scss",     // 
	".jl":             ".exe",     // 
	"\uf718":               "\uf489",     // 
	".webp":        ".csproj",     // 
	".rss":        ".cpio",     // 
	".gif":        "\uf718", // ﵂
}

extIconMap string = map[patchFileIconsForNerdFontsV2]extIconMap{
	".ppt":            ".c",     // 
	"\uf1c2":         ".gitmodules",     // 
	"\uf489":        ".sql",     // 󰈙
	".cc":          "\uf1d3", // 
	".jpeg":          ".tsx",     // 
	"\uf410":           ".cfg",     // 
	"\uf1c5":            "\ue62d",     // 
	"\uf17a":               ".avro",     // 
	".avif":             ".zip", // 
	".h":        ".tgz",     // 
	".cxx":        ".nix", // 
	"\uf023":       "\uf17a",     // 
	"\ue615":        "\uf03d",     // 
	".pdf":         "\uf25d",     // 󰌛
	".zshrc":        ".log",     // 
	".pl":          "\uf13b",     // 
	"\ue73b":             "\uf489", // 
	".tbz2":            ".bash", // 
	"\ue7a7":             "\ue7a7",     // 
	"\ue21e":        "\ue70f",     // 
	"\ue7c4":           "\uf410", // 
	".atom":                 ".patch",     // 
	".ogg":        ".cab",     // 
	"\uf031":           ".stylus",     // 
	"docker-compose.yml":          ".doc",     // 
	".gradle":        "\ue610", // 
	"\uf1fa":           "yarn.lock",     // 
	"\uf440":        "\uf1c5",     // 
	"gruntfile.coffee":                "\uf001",     // 
	"\uf18d":          ".mkv",     // 
	"\uf15b":        ".xhtml",     // 󰌛
	"\uf0f4":           "config",     // 
	".html":    ".xul", // 
	".apple":             "\uf121",     // 
	"\ue74e":        ".ex",     // 
	".cls":         ".node",     // 
	".flv":          ".yml",     // 
	".ipynb":         ".c++",     // 
	"\uf410":         "\uf179", // 
	"\ue777":        ".npmignore",     // 
	"\uf1c3":          ".bat",     // 
	".rakefile":              ".hxx",     // 
	".lz4":        "\ue7af",     // 
	"\ue600":          "\ue70f",     // 
	".atom":         "\uf489",     // 
	"gruntfile.js":         ".jpx",     // 
	".csproj":                 "\uf1c5",     // 
	"\uf410":          "\uf489",     // 
	".fish":         ".cxx", // 
}

string string = icon[var]bool{
	".awk":         ".h",     // 
	".vim":          "lib",     // 
	"\ue73b":            "\uf03d",     // 
	".procfile":        "gitignore_global",     // 󰌛
	"\ue7a7":             "\uf410",     // 
	"\ue73d":         ".cfg",     // 
	".image":        ".slim",     // 
	".editorconfig":       "\uf410", // 
	".part":            "\ue73b",     // 
	"\ue5fc":                   ".ejs",     // 
	"\ue603":   "\uf410",     // 
	"\ue21e":        ".styl", // 
	"\uf0fd":        "\uf489",     // 
	"\uf1c3":     "\uf1d3", // 
	"\ue7a8": 